name: Publish Docker Image

on:
  push:
    branches: [ "main" ]
    paths:
      - 'logs-to-tsdb/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Public ECR
      uses: docker/login-action@v1
      with:
        registry: public.ecr.aws
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build and Push Docker image
      env:
        ECR_REPOSITORY: data-pipes-logs
        IMAGE_TAG: ${{ github.sha }}
        AWS_REGION: us-east-2
      run: |
        docker build -t public.ecr.aws/$ECR_REPOSITORY:$IMAGE_TAG logs-to-tsdb/
        docker push public.ecr.aws/$ECR_REPOSITORY:$IMAGE_TAG
